"9:05am. Yesterday I read the Demon Bunny story till past 12am so I am really groggy at the moment due to insufficient sleep. Well, let me do my new routine of physical exercise and then I will chill for a while.
10:15am. I am really incredibly groggy at the moment. I way overdid it yesterday. I am not sure how I am going to get any learning done today.

Let me finish this article I am reading and then I will start.

10:25am. Forget the rest. Let me go for it.

http://us.metamath.org/mpeuni/mmset.html#overview

Let me link this again. This is what I will be reading today. I'll get Metamath and play with some of the proofs after that.

"To show you how this works in Metamath, we will break down and analyze a proof step in the proof of 2 + 2 = 4. Once you grasp this example, you will immediately be able to verify for yourself any proof in the database—no further prerequisites are needed. You may not understand what all (or any) of the symbols mean, but you can follow the rules for how they are manipulated, like game pieces, to prove theorems."

"Compare this with the years of study it might take to be able to follow and verify a proof in an advanced math textbook. Typically such proofs will omit many details, implicitly assuming you have a deep knowledge of prior material. If you want to be a mathematician, you will still need those years of study to achieve a high-level understanding. Metamath will not provide you with that. But if you just want the ability to convince yourself that a string of math symbols that mathematicians call a "theorem" is a mechanical consequence of the axioms, Metamath's proof method lets you accomplish that."

Years is not the kind of time I have to figure out these proofs. Machines will show me the way to get where I want faster.

Even though those advanced papers are giving me trouble, I keep forgetting just how advanced that material is.

Still, it will fall just like anything else once I grab a foothold.

10:45am. "When we first created the proof, why did we choose these particular substitutions for 𝐶 and 𝐹? The reason is simple—they make the proof work! But how did we know these particular substitutions should be picked, and not others? That's the hard part—we didn't know, nor did we know that oveq2i should be referenced in the second proof step, nor did we know that Step 1 would have the right expression to match the hypothesis of oveq2i. The choices were made using intelligent guesses, that were then verified to work. This is a skill a mathematician develops with experience. Some of the proofs in our database were discovered by famous mathematicians. The Metamath Proof Explorer recaptures their efforts and shows you in complete detail the proof steps and substitutions already worked out. This allows you to follow a proof even if you are not a mathematician, and be convinced that its conclusion is a consequence of the axioms."

11:05am.

```
c:\mmj2jar>java
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
```

Right now I am installing Metamath. Mario Carneiro who I've interacted with in the Lean chatroom does have his hands in a lot of places it seems. I wish he'd learn the joy of making installers rather than having users mess with the command line.

Now why am I missing Java? Well, I'll just get a new version.

11:10am. Done. Let me give it a try.

11:15am.

```
$( <MM> <PROOF_ASST> THEOREM=syllogism LOC_AFTER=

h              |- ( ph -> ps )
h              |- ( ps -> ch )
!              |- ( ph -> ( ps -> ch ) )
!              |- ( ( ph -> ps ) -> ( ph -> ch ) )
!qed           |- ( ph -> ch )

$)
```

Wow, I have no idea what this is.

11:15am. https://youtu.be/8WH4Rd4UKGE

Uf, let me watch this video. I need somebody to walk me through with this. I have no idea what any of the stuff I am looking at is.

11:40am. http://us.metamath.org/index.html#book

Let me get the book. I watched the video, but still have no idea how to find my way around.

11:55am. 12/247. This book is not too big thankfully. I should be able to get a handle on Metamath today. For the time being, let me stop so I can have breakfast."