"10:05am. I seems that the `.ionide` appears on its own. Ok, so I have the folder.
Now I need to open a repo. But before that, what does Ionide use for projects files? If I have a bunch of files, how do I build the project with them?

Hmmm, I just realized that I cannot move files into the correct order directly from the IDE. I will be missing that.

"After the project loads on Visual Studio Code, you should see the F# Solution Explorer pane on the left-hand side of your window open."

I do not see this...

- dotnet new console -lang F# -o FirstIonideProject

I think I am supposed to run this command first.

- dotnet new console -lang F# -o "The Spiral Language v0.2"

Ok, this worked for me. Nice.

10:20am. Right now I am struggling trying to figure out how to add a folder to the project.

It is already a pain in the ass compared to VS.

```
open System

let x = 2 + 2
```

Why is `open System` giving me a type error? Why it is saying that it is in `System.Xml.Xpath.Xdocument`?

"Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration."

10:25am. http://ionide.io/

Holy shit how annoying. I knew thing like this would be happening as they usually do.

https://fsharp-editing.github.io/Forge

The links on Ionide to forget are broken.

How amateurish.

10:40am. Ok, I managed to make a new project through the command palete, but there are errors everywhere.

Should I also install Fake?

10:45am.

```
#r "paket: groupref FakeBuild //"

#load "./.fake/init.fsx/intellisense.fsx"
```

```
init.fsx(2,1): error FS2301: 'paket: groupref FakeBuild //' is not a valid assembly name
```

Holy shit, this is so complex.

10:50am. http://ionide.io/docs/

So it has docs. Let me go through this.

11:05am. https://www.youtube.com/watch?v=E4LrQxElbZM
Coding F# in Visual Studio Code with Ionide

Ok, this is a failure. I am getting errors out the wazoo whatever I do. This is definitely not working for me out of the box.

Let me watch the video and then I am going to open an issue for this.

https://youtu.be/E4LrQxElbZM?t=630
"What I have here is a full console app rather than boring you with creating one..."

https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

Agh, let me install the one prerequisite the damn thing wants instead of piggibacking what I got from VS.

https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet

It seems .NET has an officially supported ML library now.

Whatever.

The time where my plan might have made sense is long gone at this point. I do not even give a shit about reasons for this or that anymore. What I want is to jack the partial evaluator into the constraint solver, and by God and Satan, I am going to do it!

11:15am. I installed .NET Core and "The type referenced through 'System.TimeSpan' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib'."

I still get the same shitty error.

Let me try restarting Windows.

...Nope. I have no idea. Let me open an issue.

12:05pm. "I created a new console project through the command palette using `F# : New Project` in VS Code, but no matter what I try I am running into strange issues. For example, the `build.fsx` file has 6 type errors, the first of which is...

>The type referenced through 'System.TimeSpan' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib'.

I thought it might be due to not having up to date .NET Core SDK so I got the fresh one and it did not make a difference.

I am not sure what to do here. Since I am at it, let me document various issues I've run into apart from the one above.

1) https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode

I've created a project using `dotnet new console -lang F# -o FirstIonideProject`

```
// Learn more about F# at http://fsharp.org

open System

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    0 // return an integer exit code
```

I am not getting an outright type error for the `open System` statement now that I've installed a new fresh .NET Core install. But when I hover the cursor over the `System`, this is what it says.

```
namespace System
Full name: System
Assembly: System.Xml.XPath.XDocument
```

No way is the assembly right here.

2) Clicking run in the F# Solution Explorer gets cleared immediately. This is regardless of here where it just prints "Hello World from F#!" for a fraction of the second before clearing, or in the other projects where it prevents me from seeing what the error is.

3) Creating a new project has issues. Even if I trigger it through the command palette, what happens is that the Ionide file getting created in the background seems to cancel it, and I have to retry it. I find this confusing.

4) I am trying to use the `> F# : New Project(ProjectScaffold)`. What happens is that the `.ionide` folder appears in the explorer window (apparently triggers by me using the command) and the project creation fails with the error `Creating project failed - directory is not empty`.

5) I can get it to create the project by deleting the `.ionide` folder manually.

6) `#r "paket: groupref FakeBuild //"` gives me the `is not valid assembly name` error.

7) Pretty much every file has errors on the open statements. For example in `init.fsx` the `open Fake.Core` gives me an error even though I have the plugin installed.

8) I am fiddling around with the standard project. For some reason `build.fsx` does not have any errors now, but only deprecated construct warnings. The boilerplate project that I've named `Test`'s `test.fs` has 3 type errors asking me to add references for .NET standard.

9) I am wondering whether changing the `Fsharp: Use SDK Scripts` has anything to do with these errors? ...Yeah, it seems that the first error (with `build.fsx`) is caused by me checking this as per instructions on the Microsoft Docs.

At least the FSI Interactive itself works, but this hasn't been a great impression on me overall. The regular VS has been driving me crazy with how it autocompletes to keywords suddenly and arbitrarily when I type fast, but I am not sure whether I can do anything to make this run.

I am willing to give it a try though. What should I do here?"

What a waste of time this is. This is issue 1279 now.

Thanks to my years of experience as a programmer and a computer user, I know this shit will make you jump through hoops. That is why I always dread trying anything new. I hate brittle installations the most of all. This is pretty much Linux-tier experience.

12:10pm. I am going to take a break here so I can have food.

Until I get a reply, I am not going to bother with this anymore. Sure the autocomplete thing is annoying, but I can live with it. Here, I can't really go anywhere as I cannot create a project properly.

I wanted to make this commit in the new Spiral repo, but let me stick it here."