"4:15pm.
```
let R' (o' : Policy) (o : Policy) (tree : GameTree) =
    u (update_at_branch_current o o' tree) tree - u o tree +
    match tree with
    | Terminal _ -> 0.0
    | Response(id, branches) -> Array.fold (fun s branch -> s + u (update_at_branch_descent o o' branch) branch - u o branch) 0.0 branches
```

Let me do R' like so.

4:20pm.

```
let R' (o' : Policy) (o : Policy) (tree : GameTree) =
    u (update_at_branch_current o o' tree) tree - u o tree +
    /// According to definition of succ which only considers opponent reach probabilities,
    /// I skip multipling by current player reach probabilities.
    let r = u' o (fun _ branch -> u (update_at_branch_descent o o' branch) branch - u o branch) tree
    printf "%f" r
    r
```

I can't believe it, but r is always 0.0 here for some reason. This should not be happening.

Actually this should be fine.

It cancels out in the body.

4:25pm. Ah, I was wrong. It is not the double counting that is the problem. Rather it seems to be the max.

4:30pm. Thunder, but let me see if I can continue for longer.

```
let R_imm (o' : Policy) (o : Policy) (tree : GameTree) = max 0.0 (u (update_at_branch_current o o' tree) tree - u o tree)

let rec R_imm_sum (o' : Policy) (o : Policy) (tree : GameTree) =
    R_imm o' o tree +
    // No multiplication by the player probabilities. It does not matter whether o' or o is passed to u'.
    u' o' (fun _ branch -> R_imm_sum o' o branch) tree
```

Why isn't this working. I understand that it is double counting, but for what reason?

4:35pm.

```
let rec R_imm_sum (o' : Policy) (o : Policy) (tree : GameTree) =
    printfn "***"
    let l = R_imm o' o tree
    printfn "l=%f" l
    l +
    // No multiplication by the player probabilities. It does not matter whether o' or o is passed to u'.
    let r = u' o' (fun _ branch -> R_imm_sum o' o branch) tree
    printfn "r=%f" r
    r
```

Ah, I see.

The error is in fact present in the previous tests, but because of the shape of testing tools, the error does not manifest.

4:50pm.

```
let rec R_imm_sum (o' : Policy) (o : Policy) (tree : GameTree) =
    match tree with
    | Terminal _ -> 0.0
    | Response _ ->
        // No multiplication by the player probabilities. It does not matter whether o' or o is passed to u'.
        R_imm o' o tree + u' o' (fun _ branch -> R_imm_sum o' o branch) tree

open FsCheck

let ``R_full<=R_imm_sum'`` ({tree=tree; policies=policies} : TreePolicies) =
    let o, o' = policies.[0], policies.[1]
    let left = R_full o' o tree
    let right = R_imm_sum o' o tree
    left <= right |@ sprintf "Failure. %f <> %f. Error bound for floats is %f." left right error_bound_for_floats

// Passes
Check.One({Config.Quick with MaxTest=1000}, ``R_full<=R_imm_sum'``)
```

I've been cleaning that test for way too long.

I finally got it.

As expected the theorem is correct, but the bounds are awful.

Could I tighten them up somehow?

4:55pm. As an example, you could make the bounds arbitrarily bad by adding many nodes with a single action.

There is something I need to do in the generator. Let me have it generate terminals in a one of fashion.

5:10pm. Let me finally commit this. I've added some comments and waxed it enough.

```
// The actual theorem is correct (unlike some of the proof steps in the paper) for the case where the opponent only has a single action.
// That having said the bound could be made arbitrarily bad by adding nodes with only a single action inside the game tree. Yuck.
// For that reason I am not interested in elaborating the test to where the opponent has multiple actions.
```

Here is what I wrote. Yeah, I am not a fan of this theorem between this and the proof issue.

It is time to start looking into the next step. That one would be Maxwell's approachability.

5:10pm. Actually no. Before I move on let me just try dividing the bound by the number of nodes. I need to see what I get.

5:40pm.

```
#load "Core.fsx"
open Core

let u' (o : Policy) f = function
    | Terminal reward -> reward
    | Response (id, branches) -> Array.fold2 (fun s policy branch -> s + f policy branch) 0.0 o.[id] branches

let rec u (o : Policy) tree = u' o (fun policy branch -> policy * u o branch) tree

let R_full (o' : Policy) (o : Policy) (tree : GameTree) = u o' tree - u o tree

let update_at_branch_current cur next = function
    | Terminal _ -> cur
    | Response (id, _) -> Map.add id (Map.find id next) cur

let R_imm (o' : Policy) (o : Policy) (tree : GameTree) = max 0.0 (u (update_at_branch_current o o' tree) tree - u o tree)

let rec R_imm_sum num_nodes (o' : Policy) (o : Policy) (tree : GameTree) =
    match tree with
    | Terminal _ -> 0.0 // This check is to avoid double counting the Terminal nodes due to the recursion. It is not an issue in the eq 9 test.
    | Response _ ->
        num_nodes := !num_nodes + 1
        // No multiplication by the player probabilities. It does not matter whether o' or o is passed to u'.
        // As it is assumed that the opponent only has one action in every node, the CFR reach probabilities are all 1 and play no role.
        R_imm o' o tree + u' o' (fun _ branch -> R_imm_sum num_nodes o' o branch) tree

open FsCheck

let ``R_full<=R_imm_sum'`` ({tree=tree; policies=policies} : TreePolicies) =
    let o, o' = policies.[0], policies.[1]
    let left = R_full o' o tree
    let r = ref 0
    let right = R_imm_sum r o' o tree
    let right = if !r > 0 then right / sqrt (float !r) else right
    left <= right |@ sprintf "Failure. %f <> %f. Error bound for floats is %f. num_nodes is %i" left right error_bound_for_floats !r

// Passes
Check.One({Config.Quick with MaxTest=10000}, ``R_full<=R_imm_sum'``)

// The actual theorem is correct (unlike some of the proof steps in the paper) for the case where the opponent only has a single action.
// That having said the bound could be made arbitrarily bad by adding nodes with only a single action inside the game tree. Yuck.
// For that reason I am not interested in elaborating the test to where the opponent has multiple actions.
```

No it is not sqrt.

Neither is it some big constant. But there is definitely a relationship between immediate sums of regrets and full regret.

5:40pm. Forget it. I won't be able to push anything here without some greater insights.

It is time to move to the next thing.

...Well today, that probably means stopping, but I will do a bit of research for the sake of tomorrow.

As expected, while this testing will be useful to stitching math together...

5:45pm.

```
Falsifiable, after 2051 tests (0 shrinks) (7554518400694520457,257335290692279553)
Last step was invoked with size of 21 and seed of (4185950197077278756,13744972331062801937):
Label of failing property: Failure. 2.326121 <> 1.744550. Error bound for floats is 0.000000.
Original:
{ policies =
            [|map
                [(0, [|0.00889; 0.92451; 0.0666|]);
                 (1, [|0.03352; 0.88357; 0.08291|]);
                 (2, [|0.15535; 0.6252; 0.21945|]);
                 (3, [|0.00428; 0.68095; 0.00164; 0.31313|]);
                 (4, [|0.21777; 0.45675; 0.32548|])];
              map
                [(0, [|0.00389; 0.08588; 0.91023|]);
                 (1, [|0.02608; 0.1538; 0.82012|]);
                 (2, [|0.55329; 0.04425; 0.40246|]);
                 (3, [|0.25022; 0.22173; 0.18358; 0.34447|]);
                 (4, [|0.44116; 0.51578; 0.04306|])]|]
  tree =
        Response
          (2,
           [|Terminal -8.6; Terminal -9.7;
             Response
               (1,
                [|Terminal 1.4;
                  Response (2,[|Terminal -5.8; Terminal 3.4; Terminal 8.1|]);
                  Response (4,[|Terminal -2.6; Terminal 6.5; Terminal -0.7|])|])|])
  infoset_sizes = [|3; 3; 3; 4; 3|] }
with exception:
System.Exception: Expected true, got false.
```

Huh what?

5:45pm. I find this really confusing. Why am I getting these errors now?

5:50pm.

```
Falsifiable, after 73666 tests (0 shrinks) (2461366301667003326,2247052889479526435)
Last step was invoked with size of 74 and seed of (14552867267767628100,3187811727436708207):
Label of failing property: Failure. 0.529533 <> 0.528974. Error bound for floats is 0.000000.
Original:
{ policies =
            [|map
                [(0, [|0.00242; 0.69999; 0.00127; 0.00248; 0.29384|]);
                 (1, [|0.00163; 0.97249; 0.00755; 0.01833|]);
                 (2, [|0.31513; 0.44683; 0.05759; 0.18045|]);
                 (3, [|0.19074; 0.80926|]); (4, [|0.37744; 0.62256|])];
              map
                [(0, [|0.08323; 0.46584; 0.18532; 0.02664; 0.23897|]);
                 (1, [|0.28288; 0.27847; 0.13788; 0.30077|]);
                 (2, [|0.00174; 0.00349; 0.96636; 0.02841|]);
                 (3, [|0.19913; 0.80087|]); (4, [|0.45761; 0.54239|])]|]
  tree =
        Response
          (4,
           [|Response
               (3,[|Terminal 4.3; Response (4,[|Terminal 1.8; Terminal 5.6|])|]);
             Terminal -3.8|])
  infoset_sizes = [|5; 4; 4; 2; 2|] }
```

So the theorem itself is false after all?

Oh yes, one thing. I really need to take advantage of that size step. What I am doing now in changing the settings by hand is ridiculous.

But, later, later.

5:55pm.

```
Falsifiable, after 6543 tests (0 shrinks) (17947101256372067428,14787371683992192641)
Last step was invoked with size of 7 and seed of (543175987540267980,12028313537534174055):
Label of failing property: Failure. 8.300594 <> 1.965112. Error bound for floats is 0.000000.
Original:
{ policies =
            [|map
                [(0, [|0.005; 0.99091; 0.00409|]); (1, [|0.91659; 0.08341|]);
                 (2, [|0.17351; 0.23036; 0.33814; 0.25799|]);
                 (3, [|0.81159; 0.18841|]);
                 (4, [|0.05401; 0.0144; 0.88171; 0.04988|])];
              map
                [(0, [|0.30333; 0.54771; 0.14896|]); (1, [|0.1455; 0.8545|]);
                 (2, [|0.03393; 0.39449; 0.52965; 0.04193|]);
                 (3, [|0.15721; 0.84279|]);
                 (4, [|0.02714; 0.30085; 0.09428; 0.57773|])]|]
  tree =
        Response
          (1,
           [|Terminal -6.3;
             Response
               (3,[|Response (1,[|Terminal 8.5; Terminal -7.1|]); Terminal 6.5|])|])
  infoset_sizes = [|3; 2; 4; 2; 4|] }
```

Here is another counter example.

6pm. Ok, now this is a surprise. Theorem 3 is outright false.

I wonder what Lanctot will have to say? Maybe it will motivate him to do that review.

Let me stop here for the day. To be honest, I thought today would be drudge work, but this finding makes it all worth it. I am quite please with this."